services:
  db:
    image: postgres:15
    container_name: focus-bear-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: focus_bear
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: focus-bear-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
